export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAIL = 'FETCH_AUTHORS_FAIL';

export const FETCH_SINGLE_AUTHOR = 'FETCH_SINGLE_AUTHOR';
export const FETCH_SINGLE_AUTHOR_SUCCESS = 'FETCH_SINGLE_AUTHOR_SUCCESS';
export const FETCH_SINGLE_AUTHOR_FAIL = 'FETCH_SINGLE_AUTHOR_FAIL';

export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const UPDATE_AUTHOR = 'UPDATE_AUTHOR';
export const INIT_AUTHOR = 'INIT_AUTHOR';

