export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_SINGLE_AUTHOR = 'FETCH_SINGLE_AUTHOR';
export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const UPDATE_AUTHOR = 'UPDATE_AUTHOR';
export const INIT_AUTHOR = 'INIT_AUTHOR';
