export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_SINGLE_CATEGORY = 'FETCH_SINGLE_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const INIT_CATEGORY = 'INIT_CATEGORY';